# http://www.appveyor.com/docs/appveyor-yml

# Test against these versions of Node.js.
environment:
  # Test against these versions of Node.js and io.js
  matrix:
    # node.js
    - nodejs_version: "8"
    - nodejs_version: "9"
    - nodejs_version: "10"
    - nodejs_version: "12"

platform:
  - x86
  - x64

# Install scripts. (runs after repo cloning)
install:
  - python -V
  - set PYTHON=python
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node -p process.arch
  - node -p process.version
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"

deploy_script:
  - IF "%APPVEYOR_REPO_TAG%" == "true" (npm run upload-windows)
  - IF NOT "%APPVEYOR_REPO_TAG%" == "true" (echo 'Not tagged, skipping deploy')